### PR TITLE
Avoid panics when merging custom annotation/labels

### LINKED ISSUE #2226: Panic when adding annotations to ConfigMap
### What happened?

When adding annotations to the cluster's config map via the [`configMap` property of `FoundationDBClusterSpec`](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/cluster_spec.md#foundationdbclusterspec), the cluster controller panics with the following:

```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 205 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:119 +0x1da
panic({0x16e5ee0?, 0x1b44360?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/FoundationDB/fdb-kubernetes-operator/controllers.mergeMap(...)
	/workspace/controllers/controllers.go:75
github.com/FoundationDB/fdb-kubernetes-operator/controllers.mergeAnnotations(...)
	/workspace/controllers/controllers.go:65
github.com/FoundationDB/fdb-kubernetes-operator/controllers.updateConfigMap.reconcile({}, {0x1b60fd8, 0xc0008e8360}, 0xc000218380, 0xc000845508, 0x0?, {{0x1b64350?, 0xc000a8e000?}, 0xc000a8e000?})
	/workspace/controllers/update_config_map.go:68 +0x526
github.com/FoundationDB/fdb-kubernetes-operator/controllers.runClusterSubReconciler({0x1b60fd8, 0xc0008e8360}, {{0x1b64350?, 0xc0008e8630?}, 0xc000a82100?}, {0x1b47820, 0x27ebd20}, 0xc000218380, 0xc000845508, 0x0)
	/workspace/controllers/cluster_controller.go:260 +0x2e6
github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile(0xc000218380, {0x1b60fd8, 0xc0008e8360}, {{{0xc0002c89d0?, 0x0?}, {0xc0005ea0d8?, 0xc0008e8360?}}})
	/workspace/controllers/cluster_controller.go:214 +0xe93
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b60fd8?, {0x1b60fd8?, 0xc0008e8360?}, {{{0xc0002c89d0?, 0x1633b60?}, {0xc0005ea0d8?, 0x4172cb?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:122 +0xa5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000349860, {0x1b61010, 0xc0004c0fa0}, {0x17441e0, 0xc0008acbe0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:323 +0x325
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000349860, {0x1b61010, 0xc0004c0fa0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:274 +0x1a8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:235 +0x73
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 92
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:231 +0x50c
```

### What did you expect to happen?

The controller should not crash, and the custom annotations should be added to the `ConfigMap` managed by the controller.

Note that this _does_ work with custom _labels._ The problem appears to be in `mergeMap`: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/0651fe849a1e9bd86f61cc3d83bad568c67ec01c/controllers/controllers.go#L68-L80

The default set of annotations for the `ConfigMap` is empty (i.e. `nil`), but the default set of labels is non-empty. Attempting to add a label adds a new value to an existing map, but adding a new annotation tries to add to a `nil` map and panics.

### How can we reproduce it (as minimally and precisely as possible)?

Add a `configMap` property to a cluster definition that adds a new annotation:

```yaml
configMap:
  metadata:
    annotations:
      panics: "unfortunately yes"
```

### Anything else we need to know?

_No response_

### FDB Kubernetes operator

Operator version 1.55.0 (but it looks like it would still be an issue in 2.0.0).

### Kubernetes version

Client Version: v1.31.4
Kustomize Version: v5.4.2
Server Version: v1.31.5-eks-8cce635

### Cloud provider

AWS/EKS

### PR DESCRIPTION
**Pull request by jon-signal**
This checks that the target maps when merging custom annotations/labels are not `nil`, thereby avoiding panics. It fixes #2226.

### CODE REVIEW

**Comment by jon-signal** [comment]
> Result: ❌ FAILED

I think this is from an old run, and I've since fixed the issue.

File: controllers/controllers.go [hunk 1]
```diff
@@ -49,19 +49,27 @@ func metadataMatches(currentMetadata metav1.ObjectMeta, desiredMetadata metav1.O
 	return containsAll(currentMetadata.Labels, desiredMetadata.Labels) && containsAll(currentMetadata.Annotations, desiredMetadata.Annotations)
 }
 
-// mergeLabels merges the the labels specified by the operator into
+// mergeLabels merges the labels specified by the operator into
 // on object's metadata.
 //
 // This will return whether the target's labels have changed.
 func mergeLabelsInMetadata(target *metav1.ObjectMeta, desired metav1.ObjectMeta) bool {
+	if target.Labels == nil && desired.Labels != nil && len(desired.Labels) > 0 {
```
Comment (johscheuer) [inline controllers/controllers.go:57]:
```suggestion
	if target.Labels == nil  {
```

We don't really care about the desired in this case, as we only set the `Labels` to an empty map in case that the `Labels` are nil. If `desired.Labels` is nil or empty, the for loop in `mergeMap` will just be a no-op (as there are no items to iterate over). Is the intention here to only initialize the map if the desired labels contain at least one element? If so, we could simplify it to `target.Labels == nil && len(desired.Labels) > 0` (the `len` method will accept a nil map).

File: controllers/controllers.go [hunk 2]
```diff
@@ -49,19 +49,27 @@ func metadataMatches(currentMetadata metav1.ObjectMeta, desiredMetadata metav1.O
...
 	return mergeMap(target.Labels, desired.Labels)
 }
 
-// mergeAnnotations merges the the annotations specified by the operator into
+// mergeAnnotations merges the annotations specified by the operator into
 // on object's metadata.
 //
 // This will return whether the target's annotations have changed.
 func mergeAnnotations(target *metav1.ObjectMeta, desired metav1.ObjectMeta) bool {
+	if target.Annotations == nil && desired.Annotations != nil && len(desired.Annotations) > 0 {
```
Comment (johscheuer) [inline controllers/controllers.go:69]:
```suggestion
	if target.Annotations == nil {
```

File: controllers/controllers.go (hunk 1 above)
Comment (jon-signal) [reply controllers/controllers.go:57]: > Is the intention here to only initialize the map if the desired labels contain at least one element?

Yes; other tests check that the target map remains `nil` if it's empty. I'll simplify the check, though!

**Review by johscheuer — APPROVED** [review]
LGTM 👍

**Comment by johscheuer** [comment]
Thanks!

**Comment by jon-signal** [comment]
Cheers! Thanks for the quick response!
