### PR TITLE
Replace any instances that have an instance ID with the wrong prefix.

### LINKED ISSUE #242: Replacing instances when changing the instance ID prefix
When we update the instance ID prefix, we're left with older instances that don't have the correct prefix. I think that the best way to fulfill the user's intention is to replace any instances that have a prefix in their instance ID that does not match the one specified.

### PR DESCRIPTION
**Pull request by brownleej**
Resolves #242

### CODE REVIEW

File: controllers/replace_misconfigured_pods.go [hunk 1]
```diff
@@ -90,39 +90,55 @@ func (c ReplaceMisconfiguredPods) Reconcile(r *FoundationDBClusterReconciler, co
...
+		if err != nil {
+			return false, err
+		}
 
-			_, idNum, err := ParseInstanceID(instanceID)
-			if err != nil {
-				return false, err
-			}
+		if instanceID != desiredInstanceID {
+			log.Info("JPB removing pod", "instanceID", instanceID, "desiredInstanceID", desiredInstanceID)
```
Comment (JoshuaMcManus) [inline controllers/replace_misconfigured_pods.go:122]: Looks like there's a leftover debug statement here
