### PR TITLE
Fixes issue #1640

### LINKED ISSUE #1640: The kubectl plugin should log a warning if a Pod is missing
### What would you like to be added/changed?

In some commands like the `restart` command missing Pods are currently ignored. We should log a warning if a Pod for a process group is missing. The code that has to be adjusted is: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/kubectl-fdb/cmd/k8s_client.go#L163.

### PR DESCRIPTION
**Pull request by manfontan**
# Description

Fixes #1640 

## Type of change

- New feature (non-breaking change which adds functionality)

## Discussion

*Are there any design details that you would like to discuss further?*

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*
- Unit tests added 
- Manual testing: 
```
$ kubectl-fdb restart -c fdb-cluster --context fdb-dev  --process-condition=MissingProcesses 
Skipping Process Group: test, because it does not have a corresponding Pod.
Skipping Process Group: test2, because it does not have a corresponding Pod.
Restart [] in cluster timeseries/foundationdb-cluster [y/n]: 
```

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?* No

## Documentation

*Did you update relevant documentation within this repository?* No

*If this change is adding new functionality, do we need to describe it in our user manual?* No

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?* N/A

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?* N/A

## Follow-up

*Are there any follow-up issues that we should pursue in the future?* No

*Does this introduce new defaults that we should re-evaluate in the future?* No

### CODE REVIEW

File: kubectl-fdb/cmd/k8s_client.go [hunk 1]
```diff
@@ -184,18 +185,24 @@ func getAllPodsFromClusterWithCondition(kubeClient client.Client, clusterName st
...
-			if pod.Labels[cluster.GetProcessGroupIDLabel()] != string(process) {
-				continue
-			}
+		podMap[pod.Labels[cluster.GetProcessGroupIDLabel()]] = pod
+	}
 
-			podNames = append(podNames, pod.Name)
+	for process := range processesSet {
+		if _, ok := podMap[string(process)]; !ok {
+			log.Printf("Pod for process group %s not found", process)
```
Comment (johscheuer) [inline kubectl-fdb/cmd/k8s_client.go:195]: Can we pass down the error o writer from the command line? Otherwise we will print this to stdout (always), which makes it harder to test and the warning should also be on stderr.

File: kubectl-fdb/cmd/k8s_client.go [hunk 2]
```diff
@@ -160,10 +160,10 @@ func executeCmd(restConfig *rest.Config, kubeClient *kubernetes.Clientset, podNa
 	return &stdout, &stderr, err
 }
 
-func getAllPodsFromClusterWithCondition(kubeClient client.Client, clusterName string, namespace string, conditions []fdbv1beta2.ProcessGroupConditionType) ([]string, error) {
+func getAllPodsFromClusterWithCondition(kubeClient client.Client, clusterName string, namespace string, conditions []fdbv1beta2.ProcessGroupConditionType) ([]string, []string, error) {
```
Comment (johscheuer) [inline kubectl-fdb/cmd/k8s_client.go:163]:
```suggestion
func getAllPodsFromClusterWithCondition(stdErr io.Writer, kubeClient client.Client, clusterName string, namespace string, conditions []fdbv1beta2.ProcessGroupConditionType) ([]string, error) {
```

I would prefer to pass down the `io.Writer` instead of returning a slice of strings.

File: kubectl-fdb/cmd/k8s_client.go [hunk 3]
```diff
@@ -181,24 +181,34 @@ func getAllPodsFromClusterWithCondition(kubeClient client.Client, clusterName st
...
-				continue
-			}
+		podMap[pod.Labels[cluster.GetProcessGroupIDLabel()]] = pod
+	}
 
-			podNames = append(podNames, pod.Name)
+	var warnings []string
+	for process := range processesSet {
+		if _, ok := podMap[string(process)]; !ok {
+			warnings = append(warnings, fmt.Sprintf("Process Group: %s, is missing pods.", process))
```
Comment (johscheuer) [inline kubectl-fdb/cmd/k8s_client.go:195]:
```suggestion
			fmt.Fprintln(stdErr, ("Process Group: %s, is missing pods.", process)
```

With the changes from above.

File: kubectl-fdb/cmd/restart.go [hunk 4]
```diff
@@ -105,10 +106,14 @@ func newRestartCmd(streams genericclioptions.IOStreams) *cobra.Command {
 					processes = append(processes, pod.Name)
 				}
 			} else if len(conditions) > 0 {
-				processes, err = getAllPodsFromClusterWithCondition(kubeClient, clusterName, namespace, conditions)
+				var warn []string
+				processes, warn, err = getAllPodsFromClusterWithCondition(kubeClient, clusterName, namespace, conditions)
```
Comment (johscheuer) [inline kubectl-fdb/cmd/restart.go:110]:
```suggestion
				processes, warn, err = getAllPodsFromClusterWithCondition(cmd.ErrOrStderr(), kubeClient, clusterName, namespace, conditions)
```

With the changes from above we can pass down the `io.Writer`.

File: kubectl-fdb/cmd/restart.go [hunk 5]
```diff
@@ -105,10 +106,14 @@ func newRestartCmd(streams genericclioptions.IOStreams) *cobra.Command {
...
 				if err != nil {
 					return err
 				}
+				if warn != nil {
```
Comment (johscheuer) [inline kubectl-fdb/cmd/restart.go:114]: This will be removed but in general I would prefer a `len(warn) > 0` instead of a nil check.

File: kubectl-fdb/cmd/k8s_client_test.go [hunk 6]
```diff
@@ -151,7 +151,7 @@ var _ = Describe("[plugin] using the Kubernetes client", func() {
 
 		DescribeTable("should show all deprecations",
 			func(tc testCase) {
-				pods, err := getAllPodsFromClusterWithCondition(k8sClient, clusterName, namespace, tc.conditions)
+				pods, _, err := getAllPodsFromClusterWithCondition(k8sClient, clusterName, namespace, tc.conditions)
```
Comment (johscheuer) [inline kubectl-fdb/cmd/k8s_client_test.go:154]: Can we build a test case where one Pod is missing and we check the output of stderr? We can use `bytes.Buffer` for the stderr `io.Writer` and check the content later, here is an example: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/kubectl-fdb/cmd/version_test.go#L44-L49.

File: kubectl-fdb/cmd/k8s_client.go [hunk 7]
```diff
@@ -181,24 +181,34 @@ func getAllPodsFromClusterWithCondition(kubeClient client.Client, clusterName st
...
+			continue
+		}
+		if podMap[string(process)].Labels[cluster.GetProcessGroupIDLabel()] != string(process) {
+			continue
 		}
+		if podMap[string(process)].Status.Phase != corev1.PodRunning {
```
Comment (johscheuer) [inline kubectl-fdb/cmd/k8s_client.go:201]: Can we write a warning here too? e.g.: `fmt.Fprintln(stdErr, ("Skipping Process Group: %s, Pod is not running, current phase: %s", process, podMap[string(process)].Status.Phase)`

File: kubectl-fdb/cmd/k8s_client.go [hunk 8]
```diff
@@ -181,24 +181,34 @@ func getAllPodsFromClusterWithCondition(kubeClient client.Client, clusterName st
...
-			if pod.Labels[cluster.GetProcessGroupIDLabel()] != string(process) {
-				continue
-			}
+		podMap[pod.Labels[cluster.GetProcessGroupIDLabel()]] = pod
+	}
 
-			podNames = append(podNames, pod.Name)
+	var warnings []string
+	for process := range processesSet {
+		if _, ok := podMap[string(process)]; !ok {
```
Comment (johscheuer) [inline kubectl-fdb/cmd/k8s_client.go:194]: If we access the pod multiple times later we should store it in a variable instead of fetching it always from the map.

File: kubectl-fdb/cmd/restart.go (hunk 5 above)
Comment (manfontan) [reply kubectl-fdb/cmd/restart.go:114]: ack

File: kubectl-fdb/cmd/k8s_client_test.go (hunk 6 above)
Comment (manfontan) [reply kubectl-fdb/cmd/k8s_client_test.go]: I am not sure how to run kubectl-fdb tests. Running make test does not execute them
```
?       github.com/FoundationDB/fdb-kubernetes-operator/kubectl-fdb     [no test files]
```

So I wrote the test adHoc.

Comment (johscheuer) [reply kubectl-fdb/cmd/k8s_client_test.go]: This is not an e2e test, everything is mocked. The plugin has no e2e tests.

Comment (manfontan) [reply kubectl-fdb/cmd/k8s_client_test.go]: Got the error locally. Sorry for the noise.

Comment (manfontan) [reply kubectl-fdb/cmd/k8s_client_test.go]: I initially wrote a passing test and looking at 
```
?       github.com/FoundationDB/fdb-kubernetes-operator/kubectl-fdb     [no test files]
```
I got confused. It has been a long day 😓

**Review by johscheuer — APPROVED** [review]
LGTM 👍 Thanks!
